workflows:
  android-kotlin-workflow:
    name: Build Black Blue App
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      java: 17
    triggering:
      events:
        - push
    scripts:
      - name: Create Basic Android Structure
        script: |
          mkdir -p app/src/main/java/com/devkurdi/black
          mv MainActivity.kt app/src/main/java/com/devkurdi/black/
          
          # دروستکرنا فایلێ build.gradle ب شێوازێ خێرا بۆ کەمپایڵێ
          echo '
          plugins {
              id "com.android.application"
              id "org.jetbrains.kotlin.android"
          }
          android {
              namespace "com.devkurdi.black"
              compileSdk 34
              defaultConfig {
                  applicationId "com.devkurdi.black"
                  minSdk 24
                  targetSdk 34
                  versionCode 1
                  versionName "1.0"
              }
          }
          ' > build.gradle
      - name: Build Android APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/**/*.apk
