workflows:
  kotlin-script-workflow:
    name: Kotlin Project Build
    max_build_duration: 10
    instance_type: mac_mini_m1
    environment:
      java: 17
    triggering:
      events:
        - push
    scripts:
      - name: Compile Kotlin Code
        script: |
          kotlinc bkack.kt -include-runtime -d myapp.jar
    artifacts:
      - myapp.jar
